<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RiskCalculatorWebForm.Tests</AssemblyName>
    <IsCodedUITest>False</IsCodedUITest>
    <OutputType>Library</OutputType>
    <ReferencePath>$(ProgramFiles)\Common Files\microsoft shared\VSTT\$(VisualStudioVersion)\UITestExtensionPackages</ReferencePath>
    <RootNamespace>RiskCalculatorWebForm.Tests</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <TestProjectType>UnitTest</TestProjectType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"></FrameworkReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config"></None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controls\"></Folder>
    <Folder Include="Pages\"></Folder>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="*"></PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="*"></PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*"></PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0"></PackageReference>
    <PackageReference Include="System.ValueTuple" Version="4.6.1"></PackageReference>
    <PackageReference Include="Moq" Version="4.20.72"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../risk-calculator-webapp/risk-calculator-webapp.csproj"></ProjectReference>
  </ItemGroup>
</Project>